<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Product>Umbraco.Community.EdgeCache.AzureFrontDoor</Product>
    <PackageId>Umbraco.Community.EdgeCache.AzureFrontDoor</PackageId>
    <Title>Edge Cache - Azure Front Door</Title>
    <Description>Azure Front Door provider for Umbraco.Community.EdgeCache.</Description>
    <PackageTags>umbraco;umbraco-marketplace;azure;azure-front-door;edge-cache</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Umbraco.Community.EdgeCache\Umbraco.Community.EdgeCache.csproj" />
  </ItemGroup>

</Project>
