<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Product>Umbraco.Community.EdgeCache.CloudFlare</Product>
    <PackageId>Umbraco.Community.EdgeCache.CloudFlare</PackageId>
    <Title>Edge Cache - CloudFlare</Title>
    <Description>CloudFlare provider for Umbraco.Community.EdgeCache.</Description>
    <PackageTags>umbraco;umbraco-marketplace;cloudflare;edge-cache</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Umbraco.Community.EdgeCache\Umbraco.Community.EdgeCache.csproj" />
  </ItemGroup>

</Project>
